language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: HDnHbJbLRCTLbL2y7s8KhVip0EN9vAUyS4QL55giW85y253Zrem455096lxa5GuIEtZ75A0VBcdmEmZ8728y2haKp+Czb31mpu61xhI3t2aXJ5MgvzRuNJXQxH9uJWPriLANpG0B3CG864Kx2tWYcNKNGmyTsnv/53CMop9wGSixoUPaem+a3AuByr4j6Se3yOlUebI4qpBcezpX+n7gBYpPJjDWVhMhwYEpqFtzqJh5+KnoPJiV5TDoqHVsr2FC8vs0qirBWrGEc1sblNWcBjq7EsNsUbRSjyy1oB8V1+cz3gdK1nNP+/cjJev7M0MGBFPQ6OBXltXcMQpbgLoCz3RyKGt2SAtOHMyZlcoXuMKbxUi/mL7tHzUVzSbtbBasQMiSFA/s16zsFu7568h9jCjbW6/m8G+effFB2YPYjEocWDM0S7ejQU1Be02uko4xFIbUPqLLBjIXYM9DqBuoRWw8cnBpSCnjNEGQ/G7KUMhTPnhpcAqhqIvSZz8ON3JOCegoEBFVzoISH/Jd2awPaB6BTS7EPUdbVir319HdK+N8nOeQgXPw5I4mqkbz2FdgXws5GlyxqkQuuOkiobRHJcgKb2y1WwbZEF58rDK4ou2rpOE5ER1rBrwVxVN9xz9VsMJ46ivZ980Wy2nsXbuHymbKkDsr8K0nLT2O32HMwKs=
  app: murmuring-caverns-00891
  on:
    branch: main
  run: rails db:migrate
env:
  global:
    secure: gZeJu+fKE1ly4zouV2EwBFafAJha1gf3wNcGLVqZTsH50ggThAGZ8i3kYicAZqjwZT9Sq4XuNcOJ6PSym2P34s6f/tVHfQBqxLecvh8Lu8y4unK6aH0vnDud4AJOo5rsgyRfuaPeQfItqv4WRqagXucISi7rXm5uc0mMvTEqtIFI7Degn2lSXlTCvqH1J0qtP1VAkCoU+mcNkpc88ac1zZg1NCeE9m92ywrCDkxOBU7br9UEp95PUgU3ra7uj2SrSxWSKQPnBNz1GRgA5Y6uQeQgaIg7jr9O+CNP5RHZFCqKNH0qrTHZp4TFJSxiKSgAyjrtOawEojZIXNgns6sTh39CJX/5wXkmSnzhf23Nf1B0PmQRkvQOWPlqGrpFk8TZjztMV1mF7v2z3xRZXcPsOH6IWH8/C/TUgwYQkK/j8a/5734eYyCdwuQcfGtc2LjRMRQihbMNgfXEpj4YVEE8NuI1s/w4HT1vqOpeDdBv9CAJ50S+7mEb4xpqW6GPQUD9FYWhdisjkM+5D8MWgxHesud7L1/zNmjK19G+JNY0dqf8iOsafKonDDapng7jgCC1nJVQQFdycJJp5UT4eAcBKLu91GAMDzMawqbKKpBNPPv9uA3ENujsxoqBUYJPABtHK5tTvjTp+xsuJzj1yGQ7M48ZJ/dJgsfQvqSBoF8pIEg=
