language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: HDnHbJbLRCTLbL2y7s8KhVip0EN9vAUyS4QL55giW85y253Zrem455096lxa5GuIEtZ75A0VBcdmEmZ8728y2haKp+Czb31mpu61xhI3t2aXJ5MgvzRuNJXQxH9uJWPriLANpG0B3CG864Kx2tWYcNKNGmyTsnv/53CMop9wGSixoUPaem+a3AuByr4j6Se3yOlUebI4qpBcezpX+n7gBYpPJjDWVhMhwYEpqFtzqJh5+KnoPJiV5TDoqHVsr2FC8vs0qirBWrGEc1sblNWcBjq7EsNsUbRSjyy1oB8V1+cz3gdK1nNP+/cjJev7M0MGBFPQ6OBXltXcMQpbgLoCz3RyKGt2SAtOHMyZlcoXuMKbxUi/mL7tHzUVzSbtbBasQMiSFA/s16zsFu7568h9jCjbW6/m8G+effFB2YPYjEocWDM0S7ejQU1Be02uko4xFIbUPqLLBjIXYM9DqBuoRWw8cnBpSCnjNEGQ/G7KUMhTPnhpcAqhqIvSZz8ON3JOCegoEBFVzoISH/Jd2awPaB6BTS7EPUdbVir319HdK+N8nOeQgXPw5I4mqkbz2FdgXws5GlyxqkQuuOkiobRHJcgKb2y1WwbZEF58rDK4ou2rpOE5ER1rBrwVxVN9xz9VsMJ46ivZ980Wy2nsXbuHymbKkDsr8K0nLT2O32HMwKs=
  app: murmuring-caverns-00891
  on:
    branch: main
  run: rails db:migrate
