language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: j5oI/Y3leRxyGeqALoqNhueR5ZTZv1jzmaHjBkUFDAfH7oaGBjnBB2sUnwvMyNeqxHPLu4kppgY8YerrVL7whUZFYKkn6gQsIyarkY2hGj93Vs7irH19IF3CSYJRa01y851+x7PsmELs/nsBxc5kPx8SSEgF2YiY9rPATPYPIKkK/2NbW4axvFkjvk1lJ1GY6gL2g4ptPnr5zdaocpQaoEXLAHxMT3S7vIAKdCmH2/uaufXNV0QfnhDjSGtTEZKbxOLp1rF/WsfJzHz8UD7OdAp0oVmvXln5S0EZ6Ibr++FJoYasL3095R4QlFrobi4WEX0oPJBQjMJINguqGkAFWpxpfbhEhm4bBlb0hYHY1azQQVN0PTKqkHamIK8w7fF9P3q7TIlrwNs9WG5EkN8+jL0wl+qyZr14+Xf3436KPj0/nkNuKdtXItJYjPrQ451dKJLlZ3v1zb7u39WgT0x0nV8XPDjN7KW+Cpd4vblt5d6IznUzxFFa/4kJQSk8Tjs56KQphIpmKhWbcLLWXuaXJrOimHL+oueXdh1PGRQLqG8MwxoMKrg3qSnLv8GxbaVZZ/MBPGiNoz8TsIzB9lfmiiSneBdSNNx+G/pnwIH9tO3wuVAim7ujjnvQWVj3nQ85Vf0CNEX+wQ2VuCpOfWb000GmouwUO8jUdb5Y5UtiI+s=
  app: murmuring-caverns-00891
  run: rails db:migrate
